// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HttpmodelErrorResponse httpmodel error response
//
// swagger:model httpmodel.ErrorResponse
type HttpmodelErrorResponse struct {

	// error
	Error *HttpmodelErrorResponseError `json:"error,omitempty"`
}

// Validate validates this httpmodel error response
func (m *HttpmodelErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HttpmodelErrorResponse) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HttpmodelErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HttpmodelErrorResponse) UnmarshalBinary(b []byte) error {
	var res HttpmodelErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HttpmodelErrorResponseError httpmodel error response error
//
// swagger:model HttpmodelErrorResponseError
type HttpmodelErrorResponseError struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this httpmodel error response error
func (m *HttpmodelErrorResponseError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HttpmodelErrorResponseError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HttpmodelErrorResponseError) UnmarshalBinary(b []byte) error {
	var res HttpmodelErrorResponseError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
