// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelPagination model pagination
//
// swagger:model model.Pagination
type ModelPagination struct {

	// next
	Next string `json:"next,omitempty"`

	// prev
	Prev string `json:"prev,omitempty"`
}

// Validate validates this model pagination
func (m *ModelPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelPagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelPagination) UnmarshalBinary(b []byte) error {
	var res ModelPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
