// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/SKF/go-utility/v2/uuid"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelEvent model event
//
// swagger:model model.Event
type ModelEvent struct {

	// content type
	ContentType string `json:"contentType,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// node Id
	NodeID uuid.UUID `json:"nodeId,omitempty"`

	// seq no
	SeqNo string `json:"seqNo,omitempty"`

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this model event
func (m *ModelEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelEvent) UnmarshalBinary(b []byte) error {
	var res ModelEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
