// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelDeleteAssetDataRequest model delete asset data request
//
// swagger:model model.DeleteAssetDataRequest
type ModelDeleteAssetDataRequest struct {

	// measurement ids
	MeasurementIds []string `json:"measurementIds"`

	// reason for delete
	ReasonForDelete string `json:"reasonForDelete,omitempty"`

	// resurrectable
	Resurrectable bool `json:"resurrectable,omitempty"`
}

// Validate validates this model delete asset data request
func (m *ModelDeleteAssetDataRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelDeleteAssetDataRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelDeleteAssetDataRequest) UnmarshalBinary(b []byte) error {
	var res ModelDeleteAssetDataRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
