// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelDeleteNodeDataRequest model delete node data request
//
// swagger:model model.DeleteNodeDataRequest
type ModelDeleteNodeDataRequest struct {

	// from
	From string `json:"from,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this model delete node data request
func (m *ModelDeleteNodeDataRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelDeleteNodeDataRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelDeleteNodeDataRequest) UnmarshalBinary(b []byte) error {
	var res ModelDeleteNodeDataRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
