// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/SKF/go-utility/v2/uuid"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelUsageCounter model usage counter
//
// swagger:model model.UsageCounter
type ModelUsageCounter struct {

	// collected date
	CollectedDate string `json:"collectedDate,omitempty"`

	// collected month
	CollectedMonth string `json:"collectedMonth,omitempty"`

	// measurement count
	MeasurementCount int64 `json:"measurementCount,omitempty"`

	// node Id
	NodeID uuid.UUID `json:"nodeId,omitempty"`
}

// Validate validates this model usage counter
func (m *ModelUsageCounter) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ModelUsageCounter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelUsageCounter) UnmarshalBinary(b []byte) error {
	var res ModelUsageCounter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
