// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelMeasurementData model measurement data
//
// swagger:model model.MeasurementData
type ModelMeasurementData struct {

	// links
	Links *ModelMeasurementLink `json:"links,omitempty"`

	// measurement Id
	// Format: uuid
	MeasurementID strfmt.UUID `json:"measurementId,omitempty"`
}

// Validate validates this model measurement data
func (m *ModelMeasurementData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMeasurementID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelMeasurementData) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

func (m *ModelMeasurementData) validateMeasurementID(formats strfmt.Registry) error {

	if swag.IsZero(m.MeasurementID) { // not required
		return nil
	}

	if err := validate.FormatOf("measurementId", "body", "uuid", m.MeasurementID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelMeasurementData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelMeasurementData) UnmarshalBinary(b []byte) error {
	var res ModelMeasurementData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
