// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelUsageCounter model usage counter
//
// swagger:model model.UsageCounter
type ModelUsageCounter struct {

	// collected date
	// Format: date-time
	CollectedDate strfmt.DateTime `json:"collectedDate,omitempty"`

	// collected month
	// Format: date-time
	CollectedMonth strfmt.DateTime `json:"collectedMonth,omitempty"`

	// measurement count
	MeasurementCount int64 `json:"measurementCount,omitempty"`

	// node Id
	// Format: uuid
	NodeID strfmt.UUID `json:"nodeId,omitempty"`
}

// Validate validates this model usage counter
func (m *ModelUsageCounter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollectedDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCollectedMonth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelUsageCounter) validateCollectedDate(formats strfmt.Registry) error {

	if swag.IsZero(m.CollectedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("collectedDate", "body", "date-time", m.CollectedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ModelUsageCounter) validateCollectedMonth(formats strfmt.Registry) error {

	if swag.IsZero(m.CollectedMonth) { // not required
		return nil
	}

	if err := validate.FormatOf("collectedMonth", "body", "date-time", m.CollectedMonth.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ModelUsageCounter) validateNodeID(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeID) { // not required
		return nil
	}

	if err := validate.FormatOf("nodeId", "body", "uuid", m.NodeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelUsageCounter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelUsageCounter) UnmarshalBinary(b []byte) error {
	var res ModelUsageCounter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
