// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelMediaMetadataDimensions model media metadata dimensions
//
// swagger:model model.MediaMetadataDimensions
type ModelMediaMetadataDimensions struct {

	// height
	Height int64 `json:"height,omitempty"`

	// ratio
	Ratio float64 `json:"ratio,omitempty"`

	// width
	Width int64 `json:"width,omitempty"`
}

// Validate validates this model media metadata dimensions
func (m *ModelMediaMetadataDimensions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelMediaMetadataDimensions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelMediaMetadataDimensions) UnmarshalBinary(b []byte) error {
	var res ModelMediaMetadataDimensions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
