// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelMedia model media
//
// swagger:model model.Media
type ModelMedia struct {

	// content type
	ContentType string `json:"contentType,omitempty"`

	// media
	Media string `json:"media,omitempty"`
}

// Validate validates this model media
func (m *ModelMedia) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelMedia) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelMedia) UnmarshalBinary(b []byte) error {
	var res ModelMedia
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
