// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/SKF/go-utility/v2/uuid"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelAssetUsageResponse model asset usage response
//
// swagger:model model.AssetUsageResponse
type ModelAssetUsageResponse struct {

	// asset Id
	AssetID uuid.UUID `json:"assetId,omitempty"`

	// collected at
	// Format: date-time
	CollectedAt strfmt.DateTime `json:"collectedAt,omitempty"`
}

// Validate validates this model asset usage response
func (m *ModelAssetUsageResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollectedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelAssetUsageResponse) validateCollectedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CollectedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("collectedAt", "body", "date-time", m.CollectedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelAssetUsageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelAssetUsageResponse) UnmarshalBinary(b []byte) error {
	var res ModelAssetUsageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
