// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelOperation model operation
//
// swagger:model model.Operation
type ModelOperation struct {

	// from
	From string `json:"from,omitempty"`

	// op
	// Required: true
	// Enum: [add remove replace move copy test]
	Op *string `json:"op"`

	// path
	// Required: true
	Path *string `json:"path"`

	// value
	Value interface{} `json:"value,omitempty"`
}

// Validate validates this model operation
func (m *ModelOperation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var modelOperationTypeOpPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["add","remove","replace","move","copy","test"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		modelOperationTypeOpPropEnum = append(modelOperationTypeOpPropEnum, v)
	}
}

const (

	// ModelOperationOpAdd captures enum value "add"
	ModelOperationOpAdd string = "add"

	// ModelOperationOpRemove captures enum value "remove"
	ModelOperationOpRemove string = "remove"

	// ModelOperationOpReplace captures enum value "replace"
	ModelOperationOpReplace string = "replace"

	// ModelOperationOpMove captures enum value "move"
	ModelOperationOpMove string = "move"

	// ModelOperationOpCopy captures enum value "copy"
	ModelOperationOpCopy string = "copy"

	// ModelOperationOpTest captures enum value "test"
	ModelOperationOpTest string = "test"
)

// prop value enum
func (m *ModelOperation) validateOpEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, modelOperationTypeOpPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ModelOperation) validateOp(formats strfmt.Registry) error {

	if err := validate.Required("op", "body", m.Op); err != nil {
		return err
	}

	// value enum
	if err := m.validateOpEnum("op", "body", *m.Op); err != nil {
		return err
	}

	return nil
}

func (m *ModelOperation) validatePath(formats strfmt.Registry) error {

	if err := validate.Required("path", "body", m.Path); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelOperation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelOperation) UnmarshalBinary(b []byte) error {
	var res ModelOperation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
