// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProblemsBasicProblem problems basic problem
//
// swagger:model problems.BasicProblem
type ProblemsBasicProblem struct {

	// CorrelationID, an unique identifier for tracing this issue in server logs.
	CorrelationID string `json:"correlationId,omitempty"`

	// Detail, a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance, a URI reference that identifies the specific resource on which the problem occurred.
	Instance string `json:"instance,omitempty"`

	// Status, the HTTP status code associated with this problem occurrence.
	Status int64 `json:"status,omitempty"`

	// Title, a short, human-readable summary of the problem type.
	// This should always be the same value for the same Type.
	Title string `json:"title,omitempty"`

	// Type, a URI reference that identifies the problem type.
	// When dereferenced this should provide human-readable documentation for the
	// problem type. When member is not present it is assumed to be "about:blank".
	Type string `json:"type,omitempty"`
}

// Validate validates this problems basic problem
func (m *ProblemsBasicProblem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProblemsBasicProblem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProblemsBasicProblem) UnmarshalBinary(b []byte) error {
	var res ProblemsBasicProblem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
